local icons_by_filename = {
  ["vitest.config.ts"] = {
    icon = "󰉁",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Vitest",
  },
  ["vite.config.ts"] = {
    icon = "󰉁",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Vite",
  },
  [".babelrc"] = {
    icon = "󰅩",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Babelrc",
  },
  [".bash_profile"] = {
    icon = "󰒓",
    color = "#89e051",
    cterm_color = "113",
    name = "BashProfile",
  },
  [".bashrc"] = {
    icon = "󰒓",
    color = "#89e051",
    cterm_color = "113",
    name = "Bashrc",
  },
  [".dockerignore"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  [".ds_store"] = {
    icon = "󰒓",
    color = "#41535b",
    cterm_color = "239",
    name = "DsStore",
  },
  [".editorconfig"] = {
    icon = "",
    color = "#41535b",
    cterm_color = "239",
    name = "EditConfig",
  },
  [".env"] = {
    icon = "󰙪",
    color = "#faf743",
    cterm_color = "227",
    name = "Env",
  },
  [".eslintrc"] = {
    icon = "󰱺",
    color = "#4b32c3",
    cterm_color = "56",
    name = "Eslintrc",
  },
  [".gitattributes"] = {
    icon = "󰊢",
    color = "#41535b",
    cterm_color = "239",
    name = "GitAttributes",
  },
  [".gitconfig"] = {
    icon = "󰒓",
    color = "#41535b",
    cterm_color = "239",
    name = "GitConfig",
  },
  [".gitignore"] = {
    icon = "󰊢",
    color = "#41535b",
    cterm_color = "239",
    name = "GitIgnore",
  },
  [".gitlab-ci.yml"] = {
    icon = "󰮠",
    color = "#e24329",
    cterm_color = "196",
    name = "GitlabCI",
  },
  [".gitmodules"] = {
    icon = "󰊢",
    color = "#41535b",
    cterm_color = "239",
    name = "GitModules",
  },
  [".gvimrc"] = {
    icon = "",
    color = "#019833",
    cterm_color = "28",
    name = "Gvimrc",
  },
  [".npmignore"] = {
    icon = "󰛷",
    color = "#E8274B",
    cterm_color = "197",
    name = "NPMIgnore",
  },
  [".npmrc"] = {
    icon = "󰛷",
    color = "#E8274B",
    cterm_color = "197",
    name = "NPMrc",
  },
  [".settings.json"] = {
    icon = "󰨞",
    color = "#854CC7",
    cterm_color = "98",
    name = "SettingsJson",
  },
  [".vimrc"] = {
    icon = "",
    color = "#019833",
    cterm_color = "28",
    name = "Vimrc",
  },
  [".zprofile"] = {
    icon = "󰒓",
    color = "#89e051",
    cterm_color = "113",
    name = "Zshprofile",
  },
  [".zshenv"] = {
    icon = "󰒓",
    color = "#89e051",
    cterm_color = "113",
    name = "Zshenv",
  },
  [".zshrc"] = {
    icon = "󰒓",
    color = "#89e051",
    cterm_color = "113",
    name = "Zshrc",
  },
  ["_gvimrc"] = {
    icon = "",
    color = "#019833",
    cterm_color = "28",
    name = "Gvimrc",
  },
  ["_vimrc"] = {
    icon = "",
    color = "#019833",
    cterm_color = "28",
    name = "Vimrc",
  },
  ["R"] = {
    icon = "󰟔",
    color = "#358a5b",
    cterm_color = "29",
    name = "R",
  },
  ["avif"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Avif",
  },
  ["brewfile"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Brewfile",
  },
  ["build"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "BazelBuild",
  },
  ["cmakelists.txt"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "CMakeLists",
  },
  ["commit_editmsg"] = {
    icon = "󰊢",
    color = "#41535b",
    cterm_color = "239",
    name = "GitCommit",
  },
  ["containerfile"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  ["copying"] = {
    icon = "󰿃",
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["copying.lesser"] = {
    icon = "󰿃",
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["docker-compose.yaml"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  ["docker-compose.yml"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  ["dockerfile"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  ["favicon.ico"] = {
    icon = "󰓎",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Favicon",
  },
  ["gemfile$"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Gemfile",
  },
  ["gnumakefile"] = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["gruntfile"] = {
    icon = "",
    color = "#e37933",
    cterm_color = "166",
    name = "Gruntfile",
  },
  ["gulpfile"] = {
    icon = "",
    color = "#cc3e44",
    cterm_color = "167",
    name = "Gulpfile",
  },
  ["license"] = {
    icon = "󰿃",
    color = "#d0bf41",
    cterm_color = "185",
    name = "License",
  },
  ["makefile"] = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["mix.lock"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "MixLock",
  },
  ["node_modules"] = {
    icon = "󰎙",
    color = "#E8274B",
    cterm_color = "197",
    name = "NodeModules",
  },
  ["package.json"] = {
    icon = "󰛷",
    color = "#e8274b",
    name = "PackageJson",
  },
  ["package-lock.json"] = {
    icon = "󰛷",
    color = "#7a0d21",
    name = "PackageLockJson",
  },
  ["procfile"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "197",
    name = "Procfile",
  },
  ["py.typed"] = {
    icon = "󰌠",
    color = "#ffbc03",
    cterm_color = "214",
    name = "Py.typed",
  },
  ["r"] = {
    icon = "󰟔",
    color = "#358a5b",
    cterm_color = "29",
    name = "R",
  },
  ["rakefile"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Rakefile",
  },
  ["rmd"] = {
    icon = "󰍔",
    color = "#519aba",
    cterm_color = "74",
    name = "Rmd",
  },
  ["svelte.config.js"] = {
    icon = "",
    color = "#ff3e00",
    cterm_color = "196",
    name = "SvelteConfig",
  },
  ["unlicense"] = {
    icon = "󰿃",
    color = "#d0bf41",
    cterm_color = "185",
    name = "License",
  },
  ["vagrantfile$"] = {
    icon = "",
    color = "#1563FF",
    cterm_color = "27",
    name = "Vagrantfile",
  },
  ["webpack"] = {
    icon = "󰜫",
    color = "#519aba",
    cterm_color = "74",
    name = "Webpack",
  },
  ["workspace"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "BazelWorkspace",
  },
}

local icons_by_file_extension = {
  ["editorconfig"] = {
    icon = "",
    color = "#41535b",
    cterm_color = "239",
    name = "EditConfig",
  },
  ["Dockerfile"] = {
    icon = "󰡨",
    color = "#458ee6",
    cterm_color = "68",
    name = "Dockerfile",
  },
  ["R"] = {
    icon = "󰟔",
    color = "#358a5b",
    cterm_color = "29",
    name = "R",
  },
  ["aac"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "Aac",
  },
  ["ai"] = {
    icon = "",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ai",
  },
  ["applescript"] = {
    icon = "",
    color = "#6d8085",
    cterm_color = "66",
    name = "AppleScript",
  },
  ["awk"] = {
    icon = "",
    color = "#4d5a5e",
    cterm_color = "240",
    name = "Awk",
  },
  ["azcli"] = {
    icon = "",
    color = "#0078d4",
    cterm_color = "32",
    name = "AzureCli",
  },
  ["bash"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "Bash",
  },
  ["bat"] = {
    icon = "󰒓",
    color = "#C1F12E",
    cterm_color = "191",
    name = "Bat",
  },
  ["bazel"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "Bazel",
  },
  ["bib"] = {
    icon = "󱉟",
    color = "#cbcb41",
    cterm_color = "185",
    name = "BibTeX",
  },
  ["bmp"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Bmp",
  },
  ["bzl"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "Bzl",
  },
  ["c"] = {
    icon = "󰙱",
    color = "#599eff",
    cterm_color = "111",
    name = "C",
  },
  ["c++"] = {
    icon = "󰙲",
    color = "#f34b7d",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cbl"] = {
    icon = "󰒓",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cc"] = {
    icon = "󰙲",
    color = "#f34b7d",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cfg"] = {
    icon = "󰈮",
    color = "#ECECEC",
    cterm_color = "255",
    name = "Configuration",
  },
  ["cjs"] = {
    icon = "󰌞",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Cjs",
  },
  ["clj"] = {
    icon = "",
    color = "#8dc149",
    cterm_color = "113",
    name = "Clojure",
  },
  ["cljc"] = {
    icon = "",
    color = "#8dc149",
    cterm_color = "113",
    name = "ClojureC",
  },
  ["cljs"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "ClojureJS",
  },
  ["cljd"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "ClojureDart",
  },
  ["cmake"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "CMake",
  },
  ["cob"] = {
    icon = "󰒓",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cobol"] = {
    icon = "󰒓",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["coffee"] = {
    icon = "",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Coffee",
  },
  ["conf"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "Conf",
  },
  ["config.ru"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "ConfigRu",
  },
  ["cp"] = {
    icon = "󰙲",
    color = "#519aba",
    cterm_color = "74",
    name = "Cp",
  },
  ["cpp"] = {
    icon = "󰙲",
    color = "#519aba",
    cterm_color = "74",
    name = "Cpp",
  },
  ["cpy"] = {
    icon = "󰒓",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cr"] = {
    icon = "",
    color = "#c8c8c8",
    cterm_color = "251",
    name = "Crystal",
  },
  ["cs"] = {
    icon = "󰌛",
    color = "#596706",
    cterm_color = "58",
    name = "Cs",
  },
  ["csh"] = {
    icon = "",
    color = "#4d5a5e",
    cterm_color = "240",
    name = "Csh",
  },
  ["cshtml"] = {
    icon = "󱦗",
    color = "#512bd4",
    cterm_color = "56",
    name = "RazorPage",
  },
  ["cson"] = {
    icon = "󰅩",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Cson",
  },
  ["csproj"] = {
    icon = "󰪮",
    color = "#512bd4",
    cterm_color = "56",
    name = "CSharpProject",
  },
  ["css"] = {
    icon = "󰌜",
    color = "#42a5f5",
    cterm_color = "75",
    name = "Css",
  },
  ["csv"] = {
    icon = "󰈙",
    color = "#89e051",
    cterm_color = "113",
    name = "Csv",
  },
  ["cts"] = {
    icon = "󰛦",
    color = "#519aba",
    cterm_color = "74",
    name = "Cts",
  },
  ["cxx"] = {
    icon = "󰙲",
    color = "#519aba",
    cterm_color = "74",
    name = "Cxx",
  },
  ["d"] = {
    icon = "",
    color = "#427819",
    cterm_color = "28",
    name = "D",
  },
  ["dart"] = {
    icon = "",
    color = "#03589C",
    cterm_color = "25",
    name = "Dart",
  },
  ["db"] = {
    icon = "󰆼",
    color = "#dad8d8",
    cterm_color = "188",
    name = "Db",
  },
  ["desktop"] = {
    icon = "󰇄",
    color = "#563d7c",
    cterm_color = "54",
    name = "DesktopEntry",
  },
  ["diff"] = {
    icon = "󰆊",
    color = "#41535b",
    cterm_color = "239",
    name = "Diff",
  },
  ["doc"] = {
    icon = "󰈬",
    color = "#185abd",
    cterm_color = "26",
    name = "Doc",
  },
  ["docx"] = {
    icon = "󰈬",
    color = "#185abd",
    cterm_color = "26",
    name = "Docx",
  },
  ["drl"] = {
    icon = "󰧑",
    color = "#ffafaf",
    cterm_color = "217",
    name = "Drools",
  },
  ["dropbox"] = {
    icon = "󰇣",
    color = "#0061FE",
    cterm_color = "27",
    name = "Dropbox",
  },
  ["dump"] = {
    icon = "󰆼",
    color = "#dad8d8",
    cterm_color = "188",
    name = "Dump",
  },
  ["edn"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Edn",
  },
  ["eex"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Eex",
  },
  ["ejs"] = {
    icon = "󰅴",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ejs",
  },
  ["elm"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Elm",
  },
  ["eot"] = {
    icon = "󰛖",
    color = "#ECECEC",
    cterm_color = "255",
    name = "EmbeddedOpenTypeFont",
  },
  ["epp"] = {
    icon = "",
    color = "#FFA61A",
    name = "Epp",
  },
  ["erb"] = {
    icon = "󰅴",
    color = "#701516",
    cterm_color = "214",
    name = "Erb",
  },
  ["erl"] = {
    icon = "",
    color = "#B83998",
    cterm_color = "163",
    name = "Erl",
  },
  ["ex"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Ex",
  },
  ["exs"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Exs",
  },
  ["f#"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Fsharp",
  },
  ["f90"] = {
    icon = "󱈚",
    color = "#734f96",
    cterm_color = "97",
    name = "Fortran",
  },
  ["flac"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "Flac",
  },
  ["fnl"] = {
    color = "#fff3d7",
    icon = "🌜",
    cterm_color = "230",
    name = "Fennel",
  },
  ["fish"] = {
    icon = "",
    color = "#4d5a5e",
    cterm_color = "240",
    name = "Fish",
  },
  ["fs"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Fs",
  },
  ["fsi"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Fsi",
  },
  ["fsscript"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Fsscript",
  },
  ["fsx"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Fsx",
  },
  ["gd"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "GDScript",
  },
  ["gemspec"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Gemspec",
  },
  ["gif"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Gif",
  },
  ["git"] = {
    icon = "󰊢",
    color = "#F14C28",
    cterm_color = "196",
    name = "GitLogo",
  },
  ["glb"] = {
    icon = "󰆦",
    color = "#FFB13B",
    cterm_color = "214",
    name = "BinaryGLTF",
  },
  ["gnumakefile"] = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["go"] = {
    icon = "󰟓",
    color = "#519aba",
    cterm_color = "74",
    name = "Go",
  },
  ["godot"] = {
    icon = "󰈮",
    color = "#6d8086",
    cterm_color = "66",
    name = "GodotProject",
  },
  ["gql"] = {
    icon = "",
    color = "#e535ab",
    cterm_color = "199",
    name = "GraphQL",
  },
  ["graphql"] = {
    icon = "",
    color = "#e535ab",
    cterm_color = "199",
    name = "GraphQL",
  },
  ["h"] = {
    icon = "󰬏",
    color = "#a074c4",
    cterm_color = "140",
    name = "H",
  },
  ["haml"] = {
    icon = "󰅴",
    color = "#eaeae1",
    cterm_color = "255",
    name = "Haml",
  },
  ["hbs"] = {
    icon = "󱗞",
    color = "#f0772b",
    cterm_color = "202",
    name = "Hbs",
  },
  ["heex"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Heex",
  },
  ["hh"] = {
    icon = "󰬏",
    color = "#a074c4",
    cterm_color = "140",
    name = "Hh",
  },
  ["hpp"] = {
    icon = "󰬏",
    color = "#a074c4",
    cterm_color = "140",
    name = "Hpp",
  },
  ["hrl"] = {
    icon = "",
    color = "#B83998",
    cterm_color = "163",
    name = "Hrl",
  },
  ["hs"] = {
    icon = "󰲒",
    color = "#a074c4",
    cterm_color = "140",
    name = "Hs",
  },
  ["htm"] = {
    icon = "󰅴",
    color = "#e34c26",
    cterm_color = "196",
    name = "Htm",
  },
  ["html"] = {
    icon = "󰌝",
    color = "#e44d26",
    cterm_color = "196",
    name = "Html",
  },
  ["huff"] = {
    icon = "󰡘",
    color = "#4242c7",
    cterm_color = "56",
    name = "Huff",
  },
  ["hurl"] = {
    icon = "",
    color = "#ff0288",
    cterm_color = "198",
    name = "Hurl",
  },
  ["hxx"] = {
    icon = "󰬏",
    color = "#a074c4",
    cterm_color = "140",
    name = "Hxx",
  },
  ["ico"] = {
    icon = "󰋹",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ico",
  },
  ["import"] = {
    icon = "󰏢",
    color = "#ECECEC",
    cterm_color = "255",
    name = "ImportConfiguration",
  },
  ["ini"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "Ini",
  },
  ["java"] = {
    icon = "󰬷",
    color = "#cc3e44",
    cterm_color = "167",
    name = "Java",
  },
  ["jl"] = {
    icon = "",
    color = "#a270ba",
    cterm_color = "133",
    name = "Jl",
  },
  ["jpeg"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Jpeg",
  },
  ["jpg"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Jpg",
  },
  ["js"] = {
    icon = "󰌞",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Js",
  },
  ["json"] = {
    icon = "󰅩",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Json",
  },
  ["json5"] = {
    icon = "󰅩",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Json5",
  },
  ["jsonc"] = {
    icon = "󰅩",
    color = "#cbcb41",
    cterm_color = "185",
    name = "Jsonc",
  },
  ["jsx"] = {
    icon = "󰜈",
    color = "#20c2e3",
    cterm_color = "45",
    name = "Jsx",
  },
  ["jxl"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "JpegXl",
  },
  ["ksh"] = {
    icon = "",
    color = "#4d5a5e",
    cterm_color = "240",
    name = "Ksh",
  },
  ["kt"] = {
    icon = "󱈙",
    color = "#7F52FF",
    cterm_color = "99",
    name = "Kotlin",
  },
  ["kts"] = {
    icon = "󱈙",
    color = "#7F52FF",
    cterm_color = "99",
    name = "KotlinScript",
  },
  ["leex"] = {
    icon = "",
    color = "#a074c4",
    cterm_color = "140",
    name = "Leex",
  },
  ["less"] = {
    icon = "󰐣",
    color = "#563d7c",
    cterm_color = "54",
    name = "Less",
  },
  ["lhs"] = {
    icon = "󰲒",
    color = "#a074c4",
    cterm_color = "140",
    name = "Lhs",
  },
  ["license"] = {
    icon = "󰿃",
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["liquid"] = {
    icon = "󰆫",
    color = "#95BF47",
    cterm_color = "106",
    name = "Liquid",
  },
  ["lock"] = {
    icon = "󰌿",
    color = "#bbbbbb",
    cterm_color = "250",
    name = "Lock",
  },
  ["log"] = {
    icon = "󰌱",
    color = "#ffffff",
    cterm_color = "231",
    name = "Log",
  },
  ["lua"] = {
    icon = "󰢱",
    color = "#51a0cf",
    cterm_color = "74",
    name = "Lua",
  },
  ["luau"] = {
    icon = "󰢱",
    color = "#51a0cf",
    cterm_color = "74",
    name = "Luau",
  },
  ["m4a"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "M4A",
  },
  ["m4v"] = {
    icon = "",
    color = "#FD971F",
    cterm_color = "208",
    name = "M4V",
  },
  ["makefile"] = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["markdown"] = {
    icon = "󰍔",
    color = "#519aba",
    cterm_color = "74",
    name = "Markdown",
  },
  ["material"] = {
    icon = "󰔉",
    color = "#B83998",
    cterm_color = "163",
    name = "Material",
  },
  ["md"] = {
    icon = "󰍔",
    color = "#ffffff",
    cterm_color = "231",
    name = "Md",
  },
  ["mdx"] = {
    icon = "󰍔",
    color = "#519aba",
    cterm_color = "74",
    name = "Mdx",
  },
  ["mint"] = {
    icon = "󰌪",
    color = "#87c095",
    cterm_color = "108",
    name = "Mint",
  },
  ["mjs"] = {
    icon = "󰌞",
    color = "#f1e05a",
    cterm_color = "185",
    name = "Mjs",
  },
  ["mk"] = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["mkv"] = {
    icon = "",
    color = "#FD971F",
    cterm_color = "208",
    name = "Mkv",
  },
  ["ml"] = {
    icon = "󰘧",
    color = "#e37933",
    cterm_color = "166",
    name = "Ml",
  },
  ["mli"] = {
    icon = "󰘧",
    color = "#e37933",
    cterm_color = "166",
    name = "Mli",
  },
  ["mo"] = {
    icon = "󰚾",
    color = "#9772FB",
    cterm_color = "135",
    name = "Motoko",
  },
  ["mov"] = {
    icon = "",
    color = "#FD971F",
    cterm_color = "208",
    name = "MOV",
  },
  ["mp3"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "Mp3",
  },
  ["mp4"] = {
    icon = "",
    color = "#FD971F",
    cterm_color = "208",
    name = "Mp4",
  },
  ["mts"] = {
    icon = "󰛦",
    color = "#519aba",
    cterm_color = "74",
    name = "Mts",
  },
  ["mustache"] = {
    icon = "󱗞",
    color = "#e37933",
    cterm_color = "166",
    name = "Mustache",
  },
  ["nim"] = {
    icon = "",
    color = "#f3d400",
    cterm_color = "220",
    name = "Nim",
  },
  ["nix"] = {
    icon = "󱄅",
    color = "#7ebae4",
    cterm_color = "110",
    name = "Nix",
  },
  ["nswag"] = {
    icon = "󰅩",
    color = "#85ea2d",
    cterm_color = "112",
    name = "Nswag",
  },
  ["ogg"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "Ogg",
  },
  ["opus"] = {
    icon = "󰈣",
    color = "#F88A02",
    cterm_color = "208",
    name = "OPUS",
  },
  ["org"] = {
    icon = "",
    color = "#77AA99",
    cterm_color = "73",
    name = "OrgMode",
  },
  ["otf"] = {
    icon = "󰛖",
    color = "#ECECEC",
    cterm_color = "255",
    name = "OpenTypeFont",
  },
  ["pck"] = {
    icon = "󰏓",
    color = "#6d8086",
    cterm_color = "66",
    name = "PackedResource",
  },
  ["pdf"] = {
    icon = "󰈦",
    color = "#b30b00",
    cterm_color = "124",
    name = "Pdf",
  },
  ["php"] = {
    icon = "󰌟",
    color = "#a074c4",
    cterm_color = "140",
    name = "Php",
  },
  ["pl"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Pl",
  },
  ["pm"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Pm",
  },
  ["png"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Png",
  },
  ["pp"] = {
    icon = "",
    color = "#FFA61A",
    name = "Pp",
  },
  ["ppt"] = {
    icon = "󰈧",
    color = "#cb4a32",
    cterm_color = "214",
    name = "Ppt",
  },
  ["prisma"] = {
    icon = "",
    color = "#ffffff",
    cterm_color = "231",
    name = "Prisma",
  },
  ["pro"] = {
    icon = "󰏒",
    color = "#e4b854",
    cterm_color = "179",
    name = "Prolog",
  },
  ["ps1"] = {
    icon = "󰨊",
    color = "#4273ca",
    cterm_color = "68",
    name = "PsScriptfile",
  },
  ["psd1"] = {
    icon = "󰨊",
    color = "#6975c4",
    cterm_color = "68",
    name = "PsManifestfile",
  },
  ["psm1"] = {
    icon = "󰨊",
    color = "#6975c4",
    cterm_color = "68",
    name = "PsScriptModulefile",
  },
  ["psb"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Psb",
  },
  ["psd"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Psd",
  },
  ["pxd"] = {
    icon = "󰌠",
    color = "#5aa7e4",
    cterm_color = "39",
    name = "Pxd",
  },
  ["pxi"] = {
    icon = "󰌠",
    color = "#5aa7e4",
    cterm_color = "39",
    name = "Pxi",
  },
  ["py"] = {
    icon = "󰌠",
    color = "#ffbc03",
    cterm_color = "214",
    name = "Py",
  },
  ["pyc"] = {
    icon = "󰌠",
    color = "#ffe291",
    cterm_color = "222",
    name = "Pyc",
  },
  ["pyd"] = {
    icon = "󰌠",
    color = "#ffe291",
    cterm_color = "222",
    name = "Pyd",
  },
  ["pyi"] = {
    icon = "󰌠",
    color = "#ffbc03",
    cterm_color = "214",
    name = "Pyi",
  },
  ["pyo"] = {
    icon = "󰌠",
    color = "#ffe291",
    cterm_color = "222",
    name = "Pyo",
  },
  ["pyx"] = {
    icon = "󰌠",
    color = "#5aa7e4",
    cterm_color = "39",
    name = "Pyx",
  },
  ["query"] = {
    icon = "󰐅",
    color = "#90a850",
    cterm_color = "107",
    name = "Query",
  },
  ["r"] = {
    icon = "󰟔",
    color = "#358a5b",
    cterm_color = "29",
    name = "R",
  },
  ["rake"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Rake",
  },
  ["razor"] = {
    icon = "󱦘",
    color = "#512bd4",
    cterm_color = "56",
    name = "RazorPage",
  },
  ["rb"] = {
    icon = "󰴭",
    color = "#701516",
    cterm_color = "52",
    name = "Rb",
  },
  ["res"] = {
    icon = "",
    color = "#cc3e44",
    cterm_color = "167",
    name = "ReScript",
  },
  ["resi"] = {
    icon = "",
    color = "#f55385",
    cterm_color = "204",
    name = "ReScriptInterface",
  },
  ["rlib"] = {
    icon = "󱘗",
    color = "#dea584",
    cterm_color = "216",
    name = "Rlib",
  },
  ["rmd"] = {
    icon = "󰍔",
    color = "#519aba",
    cterm_color = "74",
    name = "Rmd",
  },
  ["rproj"] = {
    icon = "󰗆",
    color = "#358a5b",
    cterm_color = "29",
    name = "Rproj",
  },
  ["rs"] = {
    icon = "󱘗",
    color = "#dea584",
    cterm_color = "216",
    name = "Rs",
  },
  ["rss"] = {
    icon = "󰑫",
    color = "#FB9D3B",
    cterm_color = "215",
    name = "Rss",
  },
  ["sass"] = {
    icon = "󰟬",
    color = "#f55385",
    cterm_color = "204",
    name = "Sass",
  },
  ["sbt"] = {
    icon = "",
    color = "#cc3e44",
    cterm_color = "167",
    name = "sbt",
  },
  ["scala"] = {
    icon = "",
    color = "#cc3e44",
    cterm_color = "167",
    name = "Scala",
  },
  ["scm"] = {
    icon = "󰘧",
    color = "#000000",
    cterm_color = "16",
    name = "Scheme",
  },
  ["scss"] = {
    icon = "󰟬",
    color = "#f55385",
    cterm_color = "204",
    name = "Scss",
  },
  ["sh"] = {
    icon = "",
    color = "#859900",
    cterm_color = "113",
    name = "Sh",
  },
  ["sig"] = {
    icon = "󰘧",
    color = "#e37933",
    cterm_color = "166",
    name = "Sig",
  },
  ["slim"] = {
    icon = "󰅴",
    color = "#e34c26",
    cterm_color = "196",
    name = "Slim",
  },
  ["sln"] = {
    icon = "󰨞",
    color = "#854CC7",
    cterm_color = "98",
    name = "Sln",
  },
  ["sml"] = {
    icon = "󰘧",
    color = "#e37933",
    cterm_color = "166",
    name = "Sml",
  },
  ["sol"] = {
    icon = "󰡪",
    color = "#519aba",
    cterm_color = "74",
    name = "Solidity",
  },
  ["spec.js"] = {
    icon = "󰳪",
    color = "#cbcb41",
    cterm_color = "185",
    name = "SpecJs",
  },
  ["spec.jsx"] = {
    icon = "󰳪",
    color = "#20c2e3",
    cterm_color = "45",
    name = "JavaScriptReactSpec",
  },
  ["spec.ts"] = {
    icon = "󰳪",
    color = "#519aba",
    cterm_color = "74",
    name = "SpecTs",
  },
  ["spec.tsx"] = {
    icon = "󰳪",
    color = "#1354bf",
    cterm_color = "26",
    name = "TypeScriptReactSpec",
  },
  ["sql"] = {
    icon = "󰆼",
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite"] = {
    icon = "󰆼",
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite3"] = {
    icon = "󰆼",
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["styl"] = {
    icon = "",
    color = "#8dc149",
    cterm_color = "113",
    name = "Styl",
  },
  ["sublime"] = {
    icon = "󰬚",
    color = "#e37933",
    cterm_color = "166",
    name = "Suo",
  },
  ["suo"] = {
    icon = "󰨞",
    color = "#854CC7",
    cterm_color = "98",
    name = "Suo",
  },
  ["sv"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "SystemVerilog",
  },
  ["svelte"] = {
    icon = "",
    color = "#ff3e00",
    cterm_color = "196",
    name = "Svelte",
  },
  ["svh"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "SystemVerilog",
  },
  ["svg"] = {
    icon = "",
    color = "#FFB13B",
    cterm_color = "214",
    name = "Svg",
  },
  ["swift"] = {
    icon = "󰛥",
    color = "#e37933",
    cterm_color = "166",
    name = "Swift",
  },
  ["t"] = {
    icon = "",
    color = "#519aba",
    cterm_color = "74",
    name = "Tor",
  },
  ["tbc"] = {
    icon = "󰛓",
    color = "#1e5cb3",
    cterm_color = "25",
    name = "Tcl",
  },
  ["tcl"] = {
    icon = "󰛓",
    color = "#1e5cb3",
    cterm_color = "25",
    name = "Tcl",
  },
  ["terminal"] = {
    icon = "",
    color = "#31B53E",
    cterm_color = "34",
    name = "Terminal",
  },
  ["test.js"] = {
    icon = "󰳪",
    color = "#cbcb41",
    cterm_color = "185",
    name = "TestJs",
  },
  ["test.jsx"] = {
    icon = "󰳪",
    color = "#20c2e3",
    cterm_color = "45",
    name = "JavaScriptReactTest",
  },
  ["test.ts"] = {
    icon = "󰳪",
    color = "#519aba",
    cterm_color = "74",
    name = "TestTs",
  },
  ["test.tsx"] = {
    icon = "󰳪",
    color = "#1354bf",
    cterm_color = "26",
    name = "TypeScriptReactTest",
  },
  ["tex"] = {
    icon = "󰙩",
    color = "#3D6117",
    cterm_color = "22",
    name = "Tex",
  },
  ["tf"] = {
    icon = "󰔉",
    color = "#5F43E9",
    cterm_color = "93",
    name = "Terraform",
  },
  ["tfvars"] = {
    icon = "󰈔",
    color = "#5F43E9",
    cterm_color = "93",
    name = "TFVars",
  },
  ["toml"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "Toml",
  },
  ["tres"] = {
    icon = "󰆼",
    color = "#cbcb41",
    cterm_color = "185",
    name = "TextResource",
  },
  ["ts"] = {
    icon = "󰛦",
    color = "#519aba",
    cterm_color = "74",
    name = "Ts",
  },
  ["tscn"] = {
    icon = "󰎁",
    color = "#a074c4",
    cterm_color = "140",
    name = "TextScene",
  },
  ["tsx"] = {
    icon = "󰜈",
    color = "#1354bf",
    cterm_color = "26",
    name = "Tsx",
  },
  ["ttf"] = {
    icon = "󰛖",
    color = "#ECECEC",
    cterm_color = "255",
    name = "TrueTypeFont",
  },
  ["twig"] = {
    icon = "",
    color = "#8dc149",
    cterm_color = "113",
    name = "Twig",
  },
  ["txt"] = {
    icon = "󰈙",
    color = "#89e051",
    cterm_color = "113",
    name = "Txt",
  },
  ["v"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "Verilog",
  },
  ["vala"] = {
    icon = "",
    color = "#7239b3",
    cterm_color = "91",
    name = "Vala",
  },
  ["vh"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "Verilog",
  },
  ["vhd"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "VHDL",
  },
  ["vhdl"] = {
    icon = "󰍛",
    color = "#019833",
    cterm_color = "28",
    name = "VHDL",
  },
  ["vim"] = {
    icon = "",
    color = "#019833",
    cterm_color = "28",
    name = "Vim",
  },
  ["vsh"] = {
    icon = "",
    color = "#5d87bf",
    cterm_color = "67",
    name = "Vlang",
  },
  ["vue"] = {
    icon = "󰹭",
    color = "#8dc149",
    cterm_color = "113",
    name = "Vue",
  },
  ["wav"] = {
    icon = "",
    color = "#66D8EF",
    cterm_color = "45",
    name = "Wav",
  },
  ["webm"] = {
    icon = "",
    color = "#FD971F",
    cterm_color = "208",
    name = "Webm",
  },
  ["webmanifest"] = {
    icon = "󰅩",
    color = "#f1e05a",
    cterm_color = "185",
    name = "Webmanifest",
  },
  ["webp"] = {
    icon = "󰋹",
    color = "#a074c4",
    cterm_color = "140",
    name = "Webp",
  },
  ["webpack"] = {
    icon = "󰜫",
    color = "#519aba",
    cterm_color = "74",
    name = "Webpack",
  },
  ["woff"] = {
    icon = "󰛖",
    color = "#ECECEC",
    cterm_color = "255",
    name = "WebOpenFontFormat",
  },
  ["woff2"] = {
    icon = "󰛖",
    color = "#ECECEC",
    cterm_color = "255",
    name = "WebOpenFontFormat",
  },
  ["xaml"] = {
    icon = "󰙳",
    color = "#512bd4",
    cterm_color = "56",
    name = "Xaml",
  },
  ["xcplayground"] = {
    icon = "󰛥",
    color = "#e37933",
    cterm_color = "166",
    name = "XcPlayground",
  },
  ["xls"] = {
    icon = "󰈛",
    color = "#207245",
    cterm_color = "29",
    name = "Xls",
  },
  ["xlsx"] = {
    icon = "󰈛",
    color = "#207245",
    cterm_color = "29",
    name = "Xlsx",
  },
  ["xml"] = {
    icon = "󰗀",
    color = "#e37933",
    cterm_color = "166",
    name = "Xml",
  },
  ["xul"] = {
    icon = "󰈹",
    color = "#e37933",
    cterm_color = "166",
    name = "Xul",
  },
  ["yaml"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "Yaml",
  },
  ["yml"] = {
    icon = "󰒓",
    color = "#6d8086",
    cterm_color = "66",
    name = "Yml",
  },
  ["zig"] = {
    icon = "",
    color = "#f69a1b",
    cterm_color = "172",
    name = "Zig",
  },
  ["zsh"] = {
    icon = "",
    color = "#89e051",
    cterm_color = "113",
    name = "Zsh",
  },
  ["wasm"] = {
    icon = "",
    color = "#5c4cdb",
    cterm_color = "62",
    name = "Wasm",
  },
}

return {
  icons_by_filename = icons_by_filename,
  icons_by_file_extension = icons_by_file_extension,
}
